spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://restaurant-user-management-service
          predicates:
            - Path=/users/**
        - id: menu-service
          uri: lb://restaurant-menu-management-service
          predicates:
            - Path=/menus/**
        # Add more routes as necessary
  application:
    name: gateway-service


server:
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
