spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: restaurant-menu-management-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/restaurant_menu_db?useSSL=false
#    username: microservices
#    password: MyPassword123!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
server:
  port: 1415
