spring:
  application:
    name: conf-common-services
    cloud:
      compatibility-verifier:
        enabled: false
      config:
        server:
          git:
#            uri: https://your-git-repository.com/config-repo
            cloneOnStart: true
            defaultLabel: main
server:
  port: 8888

