spring:
  application:
    name: restaurant-eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
