spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: reservation-management-service
server:
  port: 1419
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
